Add init container for experiments snapshot in Jenkins Kubernetes pod configuration
- Introduced an init container named 'init-experiments-snapshot' to validate the existence of the experiments source directory and create symbolic links for experiment snapshots.
- Updated volume mounts to include 'experiments-snapshot' for better management of experiment data.
- Adjusted permissions in the Jenkinsfile to ensure write access for the 'jnlp' container during pipeline execution.

diff --git a/jenkins-k8s-pod.yaml b/jenkins-k8s-pod.yaml
--- a/jenkins-k8s-pod.yaml
+++ b/jenkins-k8s-pod.yaml
@@ -11,6 +11,31 @@ spec:
   # The securityContext in the pod is inherited, as it becomes the default pod template
   securityContext:
     fsGroup: 1000
+  initContainers:
+    - name: init-experiments-snapshot
+      image: busybox
+      securityContext:
+        runAsUser: 2921
+        runAsGroup: 1146
+      command: ["sh"]
+      args:
+        - "-c"
+        - |
+          set -e
+          EXPERIMENTS_SOURCE_DIR="/atlas-data/gxa_codon/.snapshot/gxa_codon_2025-10-14_13:34/experiments"
+          if [ ! -d "$EXPERIMENTS_SOURCE_DIR" ]; then
+            echo "ERROR: experimentsSourceDir does not exist: $EXPERIMENTS_SOURCE_DIR" >&2
+            exit 1
+          fi
+          ln -s "$EXPERIMENTS_SOURCE_DIR"/E-* /experiments_snapshot/
+          echo "Number of experiments in snapshot: $(ls /experiments_snapshot | wc -l)"
+      volumeMounts:
+        - name: codon-volume
+          mountPath: /atlas-data/gxa_codon
+        - name: services-volume
+          mountPath: /atlas-data/services
+        - name: experiments-snapshot
+          mountPath: /experiments_snapshot
   containers:
     - name: jnlp
       resources:
@@ -40,8 +65,10 @@ spec:
       args: [ "-c", "mkdir -p /tmp/expdesign-rw && cp /test-data/expdesign/* /tmp/expdesign-rw/ ; sleep 2h" ]
       volumeMounts:
         - mountPath: /test-data/gxa/magetab
+          name: experiments-snapshot
+          readOnly: true
+        - mountPath: /atlas-data/gxa_codon
           name: codon-volume
-          subPath: .snapshot/gxa_codon_2025-10-14_13:34/experiments
           readOnly: true
         - mountPath: /test-data/expdesign
           name: services-volume
@@ -79,11 +106,12 @@ spec:
         limits:
           memory: "2Gi"
   volumes:
+    - name: experiments-snapshot
+      emptyDir: {}
     - name: codon-volume
       nfs:
         server: hh-isi-srv-vlan1496.ebi.ac.uk
         path: /ifs/public/ro/gxa_codon
-        readOnly: true
     - name: services-volume
       nfs:
         server: hh-isi-srv-vlan1496.ebi.ac.uk
